server:
  port: 7777
  origin: 'http://localhost:3000'

db:
  host: 'localhost'
  type: 'postgres'
  port: 5432
  username: 'postgres'
  password: 'root'
  synchronize: false

jwt:
  # expiresIn: 10
  expiresIn: 900
  refreshExpiresIn: 604800
  cookieExpiresIn: 604800

app:
  fallbackLanguage: 'en'
  name: 'Truthy'
  version: 'v0.1'
  description: 'Official Truthy API'
  appUrl: 'http://localhost:7777'
  frontendUrl: 'http://localhost:3000'
  sameSite: true

mail:
  host: 'smtp.mailtrap.io'
  port: 2525
  user: 'f4a511d60957e6'
  pass: '7522797b96cef0'
  from: 'truthycms'
  fromMail: 'truthycms@gmail.com'
  preview: true
  secure: false
  ignoreTLS: true
  queueName: 'truthy-mail'

queue:
  driver: 'redis'
  host: 'localhost'
  port: 6379
  db: ''
  password: ''
  username: ''

throttle:
  global:
    ttl: 60
    limit: 60
  login:
    prefix: 'login_fail_throttle'
    limit: 5
    duration: 2592000
    blockDuration: 3000

twofa:
  authenticationAppNAme: 'truthy'

winston:
  groupName: 'truthy'
  streamName: 'truthy-stream'
  awsAccessKeyId: ''
  awsSecretAccessKey: ''
  awsRegion: ''
  
